 
all:
	cd 1; gmake all
	cd 2; gmake all
	cd 3; gmake all

clean:
	cd 1; gmake clean
	cd 2; gmake clean
	cd 3; gmake clean

mycopy:
	mkdir ${HOME}/nicetext
	mkdir ${HOME}/nicetext/tutorial
	cp -R . ${HOME}/nicetext/tutorial
