
error:
	@echo 'ERROR: The purpose of this makefile is to create a type-word list to stdout'
	@echo 'try make twlist'

twlist:
	@${NICETEXT_BIN_DIR}txt2dct num_cardinal_digits num_cardinal_words num_roman_digits num_years_digits
