.\" Copyright (C) 1995-1998 Dr. George Davida and Mark T. Chapman
.\" txt2dct.1 by Mark T. Chapman
.\"
.TH TXT2DCT 1L "Aug 17, 1998 (v0.9)" NICETEXT 
.SH NAME
txt2dct
.SH SYNOPSIS
.B txt2dct file1 [file2] [file3...]
.SH DESCRIPTION
.I txt2dct
creates type-word lists from the specified set of files. 
Each file should contain one word per line where the type of the word
is the name of the file.

The output is suitable for processing by the
.I sortdct(1L)
program in the
.B NICETEXT 
system. 
.SH "EXAMPLES"
It is strongly suggested that you try the examples in the
.B tutorial 
directory of the
.B NICETEXT
distribution.
For further information, please read the documentation in the 
.B doc 
directory.
.SH "SEE ALSO"
bitcp(1L),
dct2mstr(1L),
expgram(1L),
genmodel(1L),
gramtest(1L),
impkimmo(1L),
impmsc(1L),
impwbstr(1L),
listword(1L),
nicetext(1L),
printint(1L),
scramble(1L),
sortdct(1L).

